#!/bin/sh

# Store the directory the script is running from
LOC=$(readlink -f "$0")
DIR=$(dirname "$LOC")

# Change the charachter(s) used to seperate modules. If two are used, they will be placed at the start and end.
export SEP1="["
export SEP2="]"

# Import the modules
. "$DIR/dwm_resources.sh"
. "$DIR/dwm_pulse.sh"
. "$DIR/dwm_date.sh"

# Update dwm status bar every second
while true
do
    # Append results of each func one by one to the upperbar string
    upperbar=""
    upperbar="$upperbar$(dwm_resources)"
    upperbar="$upperbar$(dwm_pulse)"
    upperbar="$upperbar$(dwm_date)"
   
    
    xsetroot -name "$upperbar"
    
    sleep 1
done
